version: '3.8'

services:
  db:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cse437group5
      POSTGRES_PASSWORD: "swe workshop"
      POSTGRES_DB: subletifydev_v2  
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
